spring:
  rabbitmq:
    host: ${RABBIT_IP:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:pass}
    url: jdbc:postgresql://${POSTGRES_IP:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
  redis:
    host: ${CACHE_IP:172.17.0.1}
    port: ${CACHE_PORT:6379}
  profiles:
    active: A
server:
  port: 8082

urls:
  content:
    base: ${CONTENT_URL:http://localhost:5003/content}

rabbitmq:
  queue: ${RABBIT_PRIME_QUEUE:test_queue}
  exchange: ${RABBIT_EXCHANGE_LOGGER:auth-topic-exchange}
  routing:
    logging: ${RABBIT_LOGGING_RK:ms.logging}
    data-provider: ${RABBIT_DATA_PROVIDER_RK:ms.dataprovider}
