spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP:172.17.0.1}:${POSTGRES_POST:5432}/${POSTGRES_DATABASE:postgres}
    password: ${POSTGRES_PASS:pass}
    username: ${POSTGRES_USER:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: ERROR
#    org.aykhan: DEBUG
#    org.hibernate: ERROR
SERVER:
  IP: ${SERVER_IP:localhost}

server:
  port: 8080
  servlet:
    context-path: /auth
